# Generated by Django 4.1.5 on 2023-05-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=120)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido_P', models.CharField(max_length=120)),
                ('apellido_M', models.CharField(max_length=120)),
                ('edad', models.IntegerField()),
                ('especialidad', models.CharField(max_length=120)),
                ('profesion', models.CharField(max_length=120)),
                ('ubicacion', models.CharField(default='', max_length=120)),
                ('credencial', models.CharField(max_length=120)),
            ],
        ),
    ]
